# Generated by Django 4.1.3 on 2022-11-23 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiderTravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField(default=False)),
                ('travel_medium', models.CharField(choices=[('BUS', 'Bus'), ('CAR', 'Car'), ('TRAIN', 'Train')], default='BUS', max_length=100)),
                ('assets_quanity', models.IntegerField(default=1)),
                ('creation_date', models.DateField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideApp.rider')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransportationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField(default=False)),
                ('travel_medium', models.CharField(choices=[('BUS', 'Bus'), ('CAR', 'Car'), ('TRAIN', 'Train')], default='BUS', max_length=100)),
                ('assets_quanity', models.IntegerField(default=1)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('TRAVEL_BAG', 'Travel Bag'), ('PACKAGE', 'Package')], default='PACKAGE', help_text='Select asset type', max_length=100)),
                ('asset_sensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'Laptop'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'Normal')], default='NORMAL', help_text='Select sensitivity', max_length=100)),
                ('whom_to_deliver', models.CharField(help_text='Name - Mobile Number', max_length=400)),
                ('creation_date', models.DateField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideApp.requester')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(default='', max_length=200)),
                ('apply_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideApp.requester')),
                ('rider_travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideApp.ridertravelinfo')),
            ],
        ),
    ]
