# Generated by Django 4.1.3 on 2022-11-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0002_requester_user_alter_application_apply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='assettransportationrequest',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='ridertravelinfo',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='requester',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
