# Generated by Django 4.1.3 on 2022-11-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0003_remove_application_apply_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='phone',
        ),
    ]
