# Generated by Django 4.1.3 on 2022-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0004_remove_requester_gender_remove_requester_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
