# Generated by Django 4.1.3 on 2022-11-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0005_alter_requester_email_alter_rider_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiderTravelInfo',
            new_name='RideTravelInfo',
        ),
    ]
