# Generated by Django 4.1.3 on 2022-12-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0006_rename_ridertravelinfo_ridetravelinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rider',
        ),
        migrations.AddField(
            model_name='application',
            name='assetTransportationRequest',
            field=models.ForeignKey(default=1234567890, on_delete=django.db.models.deletion.CASCADE, to='RideApp.assettransportationrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requester',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
