# Generated by Django 4.1.3 on 2022-12-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0007_remove_application_requester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='rider_travel_info',
            new_name='ride_travel_info',
        ),
        migrations.RemoveField(
            model_name='assettransportationrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideApp.requester'),
            preserve_default=False,
        ),
    ]
