# Generated by Django 4.1.3 on 2022-12-12 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0008_rename_rider_travel_info_application_ride_travel_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='asset_sensitivity',
            field=models.CharField(choices=[('HIGHLY SENSITIVE', 'Laptop'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'Normal')], default='NORMAL', help_text='Select sensitivity', max_length=100),
        ),
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 8, 32, 19, 526559)),
        ),
    ]
