# Generated by Django 4.1.3 on 2022-12-20 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0009_alter_assettransportationrequest_asset_sensitivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='asset_sensitivity',
            field=models.CharField(choices=[('HIGHLY_SENSITIVE', 'Highly Sensitive'), ('SENSITIVE', 'Sensitive'), ('NORMAL', 'Normal')], default='NORMAL', help_text='Select sensitivity', max_length=100),
        ),
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 43, 52, 93823)),
        ),
    ]
