# Generated by Django 4.1.3 on 2023-01-02 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0010_alter_assettransportationrequest_asset_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransportationrequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideApp.requester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assettransportationrequest',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 9, 7, 6, 865343)),
        ),
    ]
